print("Well hello there (now name yourself by your name)")
name = input("so what is your name")
print("your name now is %s" % name)
place = input("where we are?")
print("we are in %s" % place)
noun = input ("so you brought?...")
print("you brought a %s" % noun)
print("Do you know where the doctor is ?")
verb = input("no you dont then where do you think it is")
print("so the doctor %s" % verb)
verb = input("Do you think we are safe")
print("well? are you gonna be nice or be little miss/mr no help?")
print("so you think we %s safe?" % verb)
print("oh well")
print("do you have anything else?")
noun = input("yes? what is it?")
print("so you have %s" % noun)
verb = input("are you nice?")
print("so you are %s nice" % verb)
place = input("So where do you want to vist? ")
print("so the place you wanted to go is %s" % place)
game = input("What is your favorite game?")
print("so your favorite is %s awesome it mine to!" % game)
verb = input("do you wanna live?")
print(" if %s that wonderful cause no one cares" % verb)